# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: R Tools for Visual Studio Documentation 
email: rtvsuserfeedback@microsoft.com
description: > # this means to ignore newlines until "baseurl:"
    Please send us your feedback!
baseurl: "/RTVS-docs" # the subpath of your site, e.g. /blog
url: "https://microsoft.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
